2025-02-27 18:05:12,937 ERROR 3201 [Cy7QR2xmpkc2NrmwWS1WhEnC6pwwJJYJ - 76933ms POST /api/cron/latest/task/create] Error
    at Query.run (/Users/xz/Documents/dws/node_modules/sequelize/src/dialects/mysql/query.js:46:25)
    at /Users/xz/Documents/dws/node_modules/sequelize/src/sequelize.js:650:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MySQLQueryInterface.insert (/Users/xz/Documents/dws/node_modules/sequelize/src/dialects/abstract/query-interface.js:795:21)
    at async SyncTaskEntity.save (/Users/xz/Documents/dws/node_modules/sequelize/src/model.js:4153:35)
    at async Function.create (/Users/xz/Documents/dws/node_modules/sequelize/src/model.js:2305:12)
    at async TaskCreateService.createTransactionTask (/Users/xz/Documents/dws/packages/digitalAsset/src/service/task/taskCreate.ts:104:12)
    at async TaskCreateService.createLatestTransactionTask (/Users/xz/Documents/dws/packages/digitalAsset/src/service/task/taskCreate.ts:315:9)
    at async CronController.latestTaskCreate (/Users/xz/Documents/dws/apps/da-web/src/app/controller/cron.ts:15:12)
    at async CronController.Clz.<computed> (/Users/xz/Documents/dws/node_modules/@midwayjs/core/dist/service/aspectService.js:92:34) {
  name: 'SequelizeDatabaseError',
  parent: Error: Connection lost: The server closed the connection.
      at Socket.<anonymous> (/Users/xz/Documents/dws/node_modules/mysql2/lib/connection.js:101:31)
      at Socket.emit (node:events:513:28)
      at Socket.emit (node:domain:489:12)
      at TCP.<anonymous> (node:net:301:12)
      at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
    fatal: true,
    code: 'PROTOCOL_CONNECTION_LOST',
    sql: 'INSERT INTO `sync_task` (`task_id`,`task_status`,`task_type`,`address`,`address_id`,`sync_start_time`,`sync_end_time`,`data_source`,`created_at`,`updated_at`) VALUES (DEFAULT,?,?,?,?,?,?,?,?,?);',
    parameters: [
      'wait',
      'ALEO',
      'aleo1320rutvpmn4tuu6zvyfxnea37290zrmrmluukf40a9pns5httygs3pq6mu',
      '1',
      '2024-02-28 18:03:56',
      '2025-02-27 17:58:56',
      'Aleo123',
      '2025-02-27 18:05:12',
      '2025-02-27 18:05:12'
    ]
  },
  original: Error: Connection lost: The server closed the connection.
      at Socket.<anonymous> (/Users/xz/Documents/dws/node_modules/mysql2/lib/connection.js:101:31)
      at Socket.emit (node:events:513:28)
      at Socket.emit (node:domain:489:12)
      at TCP.<anonymous> (node:net:301:12)
      at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
    fatal: true,
    code: 'PROTOCOL_CONNECTION_LOST',
    sql: 'INSERT INTO `sync_task` (`task_id`,`task_status`,`task_type`,`address`,`address_id`,`sync_start_time`,`sync_end_time`,`data_source`,`created_at`,`updated_at`) VALUES (DEFAULT,?,?,?,?,?,?,?,?,?);',
    parameters: [
      'wait',
      'ALEO',
      'aleo1320rutvpmn4tuu6zvyfxnea37290zrmrmluukf40a9pns5httygs3pq6mu',
      '1',
      '2024-02-28 18:03:56',
      '2025-02-27 17:58:56',
      'Aleo123',
      '2025-02-27 18:05:12',
      '2025-02-27 18:05:12'
    ]
  },
  sql: 'INSERT INTO `sync_task` (`task_id`,`task_status`,`task_type`,`address`,`address_id`,`sync_start_time`,`sync_end_time`,`data_source`,`created_at`,`updated_at`) VALUES (DEFAULT,?,?,?,?,?,?,?,?,?);',
  parameters: [
    'wait',
    'ALEO',
    'aleo1320rutvpmn4tuu6zvyfxnea37290zrmrmluukf40a9pns5httygs3pq6mu',
    '1',
    '2024-02-28 18:03:56',
    '2025-02-27 17:58:56',
    'Aleo123',
    '2025-02-27 18:05:12',
    '2025-02-27 18:05:12'
  ]
}
